# Generated by Django 5.1.4 on 2025-01-12 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf_site', '0002_placeorder_service_placeorderservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='SEO-заголовок для страницы или поста.', max_length=255)),
                ('description', models.TextField(help_text='SEO-описание для страницы или поста, обычно около 150-160 символов.')),
                ('keywords', models.CharField(blank=True, help_text='Кома-разделенный список SEO-ключевых слов.', max_length=255)),
            ],
            options={
                'verbose_name': 'SEO-детали',
                'verbose_name_plural': 'SEO-детали',
            },
        ),
        migrations.AlterModelOptions(
            name='placeorderservice',
            options={'verbose_name': 'Выбранная услуга', 'verbose_name_plural': 'Выбранная услуга'},
        ),
        migrations.AlterField(
            model_name='placeorder',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='placeorder',
            name='msg',
            field=models.TextField(blank=True, null=True, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='placeorder',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='placeorder',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='placeorderservice',
            name='place_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='place_order_service', to='conf_site.placeorder', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='placeorderservice',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conf_site.service', verbose_name='Услуга'),
        ),
    ]
