# Generated by Django 5.1.4 on 2025-01-13 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf_site', '0003_seodetails_alter_placeorderservice_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание'),
        ),
        migrations.CreateModel(
            name='RequirementService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Краткое описание')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_req', to='conf_site.service', verbose_name='Услугм')),
            ],
            options={
                'verbose_name': 'Требование к обслуживанию',
                'verbose_name_plural': 'Требование к обслуживанию',
            },
        ),
    ]
