# Generated by Django 5.1.4 on 2025-01-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf_site', '0004_alter_service_description_requirementservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Заголовок', max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': '4. Контакная информация',
                'verbose_name_plural': '4. Контакная информация',
            },
        ),
    ]
