# Generated by Django 5.1.4 on 2025-01-14 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf_site', '0006_alter_seodetails_options_alter_contacts_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seodetails',
            name='description',
            field=models.TextField(verbose_name='SEO-описание для страницы или поста, обычно около 150-160 символов.'),
        ),
        migrations.AlterField(
            model_name='seodetails',
            name='keywords',
            field=models.CharField(blank=True, max_length=255, verbose_name='Кома-разделенный список SEO-ключевых слов.'),
        ),
        migrations.AlterField(
            model_name='seodetails',
            name='title',
            field=models.CharField(max_length=255, verbose_name='SEO-заголовок для страницы или поста.'),
        ),
    ]
