# Generated by Django 5.1.4 on 2025-01-15 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf_site', '0009_alter_service_options_alter_servicename_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirementservice',
            name='name',
            field=models.CharField(default=1, max_length=250, verbose_name='Краткое описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requirementservice',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='service_req', to='conf_site.service', verbose_name='Услугм'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seodetails',
            name='keywords',
            field=models.CharField(max_length=255, verbose_name='SEO-ключевых слов.'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(default=1, max_length=500, verbose_name='название услуги'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicecarousel',
            name='image',
            field=models.ImageField(default=1, upload_to='service/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
