# Generated by Django 5.1.4 on 2025-01-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf_site', '0011_alter_servicename_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Название услуги'),
        ),
    ]
